apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: frontend-web
